//! Unified method handle for local (server) and remote (client) modes.
//!
//! [`InterfaceMethod`] is the field type generated by the `#[service]` macro
//! for unified service structs. In local mode it wraps a [`RequestStream`]
//! for receiving requests; in remote mode it wraps a [`ServiceEndpoint`]
//! for sending requests.

use std::rc::Rc;
use std::time::Duration;

use serde::Serialize;
use serde::de::DeserializeOwned;

use super::net_notified_queue::NetNotifiedQueue;
use super::reply_future::ReplyFuture;
use super::reply_promise::ReplyPromise;
use super::request_stream::{RequestEnvelope, RequestStream};
use super::rpc_error::RpcError;
use super::service_endpoint::ServiceEndpoint;
use crate::Endpoint;
use crate::error::MessagingError;

/// Unified method handle for both local (server) and remote (client) modes.
///
/// In **local mode**, wraps a [`RequestStream`] for receiving incoming requests
/// with reply promises.
///
/// In **remote mode**, wraps a [`ServiceEndpoint`] for sending requests with
/// various delivery modes.
///
/// # Panics
///
/// Calling server methods (`recv`, `try_recv`, etc.) on a remote-mode handle,
/// or client methods (`send`, `get_reply`, etc.) on a local-mode handle,
/// will panic. Use [`is_remote()`](Self::is_remote) to check.
pub struct InterfaceMethod<Req, Resp> {
    inner: InterfaceMethodInner<Req, Resp>,
}

enum InterfaceMethodInner<Req, Resp> {
    Local {
        stream: RequestStream<Req, Resp>,
    },
    Remote {
        endpoint: ServiceEndpoint<Req, Resp>,
    },
}

// ============================================================================
// Constructors and shared methods
// ============================================================================

impl<Req, Resp> InterfaceMethod<Req, Resp> {
    /// Create a local-mode (server) interface method from a [`RequestStream`].
    pub fn local(stream: RequestStream<Req, Resp>) -> Self {
        Self {
            inner: InterfaceMethodInner::Local { stream },
        }
    }

    /// Create a remote-mode (client) interface method from a [`ServiceEndpoint`].
    pub fn remote(endpoint: ServiceEndpoint<Req, Resp>) -> Self {
        Self {
            inner: InterfaceMethodInner::Remote { endpoint },
        }
    }

    /// Returns `true` if this is a remote (client) endpoint.
    pub fn is_remote(&self) -> bool {
        matches!(self.inner, InterfaceMethodInner::Remote { .. })
    }

    /// Get the endpoint for this method (works in both modes).
    pub fn endpoint(&self) -> &Endpoint {
        match &self.inner {
            InterfaceMethodInner::Local { stream } => stream.endpoint(),
            InterfaceMethodInner::Remote { endpoint } => endpoint.endpoint(),
        }
    }
}

// ============================================================================
// Server-side methods — unconstrained (local mode only)
// ============================================================================

impl<Req, Resp> InterfaceMethod<Req, Resp> {
    /// Get a reference to the internal queue (local mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a remote-mode handle.
    pub fn queue(&self) -> Rc<NetNotifiedQueue<RequestEnvelope<Req>>> {
        match &self.inner {
            InterfaceMethodInner::Local { stream } => stream.queue(),
            InterfaceMethodInner::Remote { .. } => {
                panic!("InterfaceMethod::queue() called on a remote endpoint")
            }
        }
    }
}

// ============================================================================
// Server-side methods — constrained (local mode only)
// ============================================================================

impl<Req, Resp> InterfaceMethod<Req, Resp>
where
    Req: DeserializeOwned + 'static,
    Resp: Serialize + 'static,
{
    /// Receive the next request with its reply promise (local mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a remote-mode handle.
    pub async fn recv(&self) -> Option<(Req, ReplyPromise<Resp>)> {
        match &self.inner {
            InterfaceMethodInner::Local { stream } => stream.recv().await,
            InterfaceMethodInner::Remote { .. } => {
                panic!("InterfaceMethod::recv() called on a remote endpoint")
            }
        }
    }

    /// Try to receive a request without blocking (local mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a remote-mode handle.
    pub fn try_recv(&self) -> Option<(Req, ReplyPromise<Resp>)> {
        match &self.inner {
            InterfaceMethodInner::Local { stream } => stream.try_recv(),
            InterfaceMethodInner::Remote { .. } => {
                panic!("InterfaceMethod::try_recv() called on a remote endpoint")
            }
        }
    }
}

// ============================================================================
// Client-side methods (remote mode only)
// ============================================================================

impl<Req, Resp> InterfaceMethod<Req, Resp>
where
    Req: Serialize + 'static,
    Resp: DeserializeOwned + 'static,
{
    /// Fire-and-forget delivery (remote mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a local-mode handle.
    pub fn send(&self, req: Req) -> Result<(), RpcError> {
        match &self.inner {
            InterfaceMethodInner::Remote { endpoint } => endpoint.send(req),
            InterfaceMethodInner::Local { .. } => {
                panic!("InterfaceMethod::send() called on a local endpoint")
            }
        }
    }

    /// At-most-once delivery (remote mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a local-mode handle.
    pub async fn try_get_reply(&self, req: Req) -> Result<Resp, RpcError> {
        match &self.inner {
            InterfaceMethodInner::Remote { endpoint } => endpoint.try_get_reply(req).await,
            InterfaceMethodInner::Local { .. } => {
                panic!("InterfaceMethod::try_get_reply() called on a local endpoint")
            }
        }
    }

    /// At-least-once delivery (remote mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a local-mode handle.
    pub async fn get_reply(&self, req: Req) -> Result<Resp, RpcError> {
        match &self.inner {
            InterfaceMethodInner::Remote { endpoint } => endpoint.get_reply(req).await,
            InterfaceMethodInner::Local { .. } => {
                panic!("InterfaceMethod::get_reply() called on a local endpoint")
            }
        }
    }

    /// At-least-once delivery with sustained failure timeout (remote mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a local-mode handle.
    pub async fn get_reply_unless_failed_for(
        &self,
        req: Req,
        sustained_failure_duration: Duration,
    ) -> Result<Resp, RpcError> {
        match &self.inner {
            InterfaceMethodInner::Remote { endpoint } => {
                endpoint
                    .get_reply_unless_failed_for(req, sustained_failure_duration)
                    .await
            }
            InterfaceMethodInner::Local { .. } => {
                panic!("InterfaceMethod::get_reply_unless_failed_for() called on a local endpoint")
            }
        }
    }

    /// Send a typed request and return a raw [`ReplyFuture`] (remote mode only).
    ///
    /// # Panics
    ///
    /// Panics if called on a local-mode handle.
    pub fn send_request(&self, req: Req) -> Result<ReplyFuture<Resp>, MessagingError> {
        match &self.inner {
            InterfaceMethodInner::Remote { endpoint } => endpoint.send_request(req),
            InterfaceMethodInner::Local { .. } => {
                panic!("InterfaceMethod::send_request() called on a local endpoint")
            }
        }
    }
}

// ============================================================================
// Trait implementations
// ============================================================================

impl<Req, Resp> Clone for InterfaceMethod<Req, Resp> {
    fn clone(&self) -> Self {
        Self {
            inner: match &self.inner {
                InterfaceMethodInner::Local { stream } => InterfaceMethodInner::Local {
                    stream: stream.clone(),
                },
                InterfaceMethodInner::Remote { endpoint } => InterfaceMethodInner::Remote {
                    endpoint: endpoint.clone(),
                },
            },
        }
    }
}

impl<Req, Resp> std::fmt::Debug for InterfaceMethod<Req, Resp> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.inner {
            InterfaceMethodInner::Local { stream } => f
                .debug_struct("InterfaceMethod::Local")
                .field("stream", stream)
                .finish(),
            InterfaceMethodInner::Remote { endpoint } => f
                .debug_struct("InterfaceMethod::Remote")
                .field("endpoint", endpoint)
                .finish(),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::net::{IpAddr, Ipv4Addr};
    use std::rc::Rc;

    use serde::{Deserialize, Serialize};

    use super::*;
    use crate::rpc::test_support::make_transport;
    use crate::rpc::transport_handle::TransportHandle;
    use crate::{JsonCodec, NetworkAddress, UID};

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    struct TestReq {
        value: u32,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    struct TestResp {
        result: u32,
    }

    fn test_endpoint() -> Endpoint {
        let addr = NetworkAddress::new(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1)), 4500);
        Endpoint::new(addr, UID::new(1, 1))
    }

    fn make_handle() -> Rc<dyn TransportHandle> {
        let transport = make_transport();
        transport as Rc<dyn TransportHandle>
    }

    #[test]
    fn test_local_mode_is_not_remote() {
        let handle = make_handle();
        let stream = RequestStream::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::local(stream);
        assert!(!method.is_remote());
    }

    #[test]
    fn test_remote_mode_is_remote() {
        let handle = make_handle();
        let ep = ServiceEndpoint::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::remote(ep);
        assert!(method.is_remote());
    }

    #[test]
    fn test_endpoint_works_both_modes() {
        let handle = make_handle();
        let endpoint = test_endpoint();

        let stream = RequestStream::<TestReq, TestResp>::new(
            endpoint.clone(),
            JsonCodec,
            Rc::clone(&handle),
        );
        let local = InterfaceMethod::local(stream);
        assert_eq!(local.endpoint().token, endpoint.token);

        let ep = ServiceEndpoint::<TestReq, TestResp>::new(endpoint.clone(), JsonCodec, handle);
        let remote = InterfaceMethod::remote(ep);
        assert_eq!(remote.endpoint().token, endpoint.token);
    }

    #[test]
    #[should_panic(expected = "recv")]
    fn test_recv_panics_on_remote() {
        let handle = make_handle();
        let ep = ServiceEndpoint::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::remote(ep);
        let _ = method.try_recv();
    }

    #[test]
    #[should_panic(expected = "send")]
    fn test_send_panics_on_local() {
        let handle = make_handle();
        let stream = RequestStream::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::local(stream);
        let _ = method.send(TestReq { value: 1 });
    }

    #[test]
    fn test_clone_local() {
        let handle = make_handle();
        let stream = RequestStream::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::local(stream);
        let cloned = method.clone();
        assert!(!cloned.is_remote());
        assert_eq!(cloned.endpoint().token, method.endpoint().token);
    }

    #[test]
    fn test_clone_remote() {
        let handle = make_handle();
        let ep = ServiceEndpoint::<TestReq, TestResp>::new(test_endpoint(), JsonCodec, handle);
        let method = InterfaceMethod::remote(ep);
        let cloned = method.clone();
        assert!(cloned.is_remote());
        assert_eq!(cloned.endpoint().token, method.endpoint().token);
    }
}
