//! Server-side method handle wrapping a [`RequestStream`].
//!
//! Generated by the `#[service]` macro for each method on the local
//! (server) struct. The companion type for client-side handles is
//! [`RemoteMethod`](super::remote_method::RemoteMethod).

use std::rc::Rc;

use serde::Serialize;
use serde::de::DeserializeOwned;

use super::net_notified_queue::NetNotifiedQueue;
use super::reply_promise::ReplyPromise;
use super::request_stream::{RequestEnvelope, RequestStream};
use crate::Endpoint;

/// Server-side method handle for receiving requests with reply promises.
pub struct LocalMethod<Req, Resp> {
    stream: RequestStream<Req, Resp>,
}

impl<Req, Resp> LocalMethod<Req, Resp> {
    /// Wrap an existing [`RequestStream`].
    pub fn new(stream: RequestStream<Req, Resp>) -> Self {
        Self { stream }
    }

    /// Get the endpoint at which this method is registered.
    pub fn endpoint(&self) -> &Endpoint {
        self.stream.endpoint()
    }

    /// Get a reference to the internal queue.
    pub fn queue(&self) -> Rc<NetNotifiedQueue<RequestEnvelope<Req>>> {
        self.stream.queue()
    }

    /// Close the stream.
    pub fn close(&self) {
        self.stream.close();
    }

    /// Check if the stream is closed.
    pub fn is_closed(&self) -> bool {
        self.stream.is_closed()
    }

    /// Check if the stream is empty.
    pub fn is_empty(&self) -> bool {
        self.stream.is_empty()
    }

    /// Get the number of pending requests.
    pub fn len(&self) -> usize {
        self.stream.len()
    }
}

impl<Req, Resp> LocalMethod<Req, Resp>
where
    Req: DeserializeOwned + 'static,
    Resp: Serialize + 'static,
{
    /// Receive the next request with its reply promise.
    pub async fn recv(&self) -> Option<(Req, ReplyPromise<Resp>)> {
        self.stream.recv().await
    }

    /// Try to receive a request without blocking.
    pub fn try_recv(&self) -> Option<(Req, ReplyPromise<Resp>)> {
        self.stream.try_recv()
    }

    /// Try to receive a request without blocking, using a custom sender for replies.
    pub fn try_recv_with_sender<F>(&self, sender: F) -> Option<(Req, ReplyPromise<Resp>)>
    where
        F: FnOnce(&Endpoint, &[u8]) + 'static,
    {
        self.stream.try_recv_with_sender(sender)
    }
}

impl<Req, Resp> Clone for LocalMethod<Req, Resp> {
    fn clone(&self) -> Self {
        Self {
            stream: self.stream.clone(),
        }
    }
}

impl<Req, Resp> std::fmt::Debug for LocalMethod<Req, Resp> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LocalMethod")
            .field("stream", &self.stream)
            .finish()
    }
}
