//! Client-side method handle wrapping a [`ServiceEndpoint`].
//!
//! Generated by the `#[service]` macro for each method on the client
//! struct. The companion type for server-side handles is
//! [`LocalMethod`](super::local_method::LocalMethod).

use std::time::Duration;

use serde::Serialize;
use serde::de::DeserializeOwned;

use super::reply_future::ReplyFuture;
use super::rpc_error::RpcError;
use super::service_endpoint::ServiceEndpoint;
use crate::Endpoint;
use crate::error::MessagingError;

/// Client-side method handle for sending requests with various delivery modes.
pub struct RemoteMethod<Req, Resp> {
    endpoint: ServiceEndpoint<Req, Resp>,
}

impl<Req, Resp> RemoteMethod<Req, Resp> {
    /// Wrap an existing [`ServiceEndpoint`].
    pub fn new(endpoint: ServiceEndpoint<Req, Resp>) -> Self {
        Self { endpoint }
    }

    /// Get the endpoint targeted by this method.
    pub fn endpoint(&self) -> &Endpoint {
        self.endpoint.endpoint()
    }
}

impl<Req, Resp> RemoteMethod<Req, Resp>
where
    Req: Serialize + 'static,
    Resp: DeserializeOwned + 'static,
{
    /// Fire-and-forget delivery.
    pub fn send(&self, req: Req) -> Result<(), RpcError> {
        self.endpoint.send(req)
    }

    /// At-most-once delivery.
    pub async fn try_get_reply(&self, req: Req) -> Result<Resp, RpcError> {
        self.endpoint.try_get_reply(req).await
    }

    /// At-least-once delivery.
    pub async fn get_reply(&self, req: Req) -> Result<Resp, RpcError> {
        self.endpoint.get_reply(req).await
    }

    /// At-least-once delivery with a sustained-failure timeout.
    pub async fn get_reply_unless_failed_for(
        &self,
        req: Req,
        sustained_failure_duration: Duration,
    ) -> Result<Resp, RpcError> {
        self.endpoint
            .get_reply_unless_failed_for(req, sustained_failure_duration)
            .await
    }

    /// Send a typed request and return a raw [`ReplyFuture`].
    pub fn send_request(&self, req: Req) -> Result<ReplyFuture<Resp>, MessagingError> {
        self.endpoint.send_request(req)
    }
}

impl<Req, Resp> Clone for RemoteMethod<Req, Resp> {
    fn clone(&self) -> Self {
        Self {
            endpoint: self.endpoint.clone(),
        }
    }
}

impl<Req, Resp> std::fmt::Debug for RemoteMethod<Req, Resp> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RemoteMethod")
            .field("endpoint", &self.endpoint)
            .finish()
    }
}
