//! The `sim-rpc-interfaces` campaign (#215): interfaces as data across
//! same-address restarts, recruitment and forwarding to a third
//! participant.
//!
//! Roles:
//!
//! - **participant** ([`Participant`], three of them): one runtime per
//!   boot at the same `ip:port`. It serves a base role instance (the
//!   `Role` interface, generated by `#[moonpool_rpc::service]`) and
//!   publishes it through a well-known directory; a well-known recruiter
//!   creates a fresh role instance per configuration and returns its
//!   publication; a well-known dismissal endpoint drops one.
//! - **third** ([`Third`]): adopts recruited members whose interfaces
//!   arrive inside a request, and calls them through its own runtime.
//! - **workload** ([`InterfacesWorkload`], "B"): a client that survives
//!   every restart. It learns interfaces only from directories and
//!   recruiters (never refreshed by the transport), keeps every learned
//!   publication stored as bytes, and calls current and stale ones.
//!
//! **Oracles** ([`state::Ledger`], written outside the transport): the
//! boot counter each participant bumps before touching the network, the
//! publication ledger each publisher writes when it registers, and the
//! execution ledger each handler writes when it runs. A handler asserts on
//! the spot that the request's reference named its own boot and instance
//! and that its boot is still the participant's current one (no task of a
//! crashed boot runs); the workload asserts that every learned interface
//! was published by the boot it names, that every stale refusal names a
//! boot that really ended, that replies come from the publishing instance,
//! and at the end judges every call against the execution ledger.
//!
//! **Faults.** A reboot script ([`InterfaceFaults`]) restarts participants
//! at their own address all through the chaos window (held-down crashes,
//! in-place reboots, graceful shutdowns); participants may delay their
//! registrations after a boot (BUGGIFY); swarm network chaos with knob
//! spikes.

mod faults;
pub mod messages;
mod participant;
pub mod state;
mod third;
mod workload;

use std::sync::{Arc, Mutex};
use std::time::Duration;

use moonpool_sim::{Chaos, ChaosMode, SimulationBuilder};

pub use faults::InterfaceFaults;
pub use participant::Participant;
pub use third::Third;
pub use workload::{InterfaceOp, InterfacesConfig, InterfacesWorkload};

/// One finished run as the workload saw it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfacesRecord {
    /// One line per operation: id, operation, outcome.
    pub history: Vec<String>,
    /// Participant restarts over the run.
    pub restarts: u64,
}

/// Where finished runs are appended, for tests to inspect.
pub type InterfacesRecords = Arc<Mutex<Vec<InterfacesRecord>>>;

/// The campaign's builder without an iteration policy.
#[must_use]
pub fn interfaces_campaign(
    config: InterfacesConfig,
    records: &InterfacesRecords,
) -> SimulationBuilder {
    let records = Arc::clone(records);
    SimulationBuilder::new()
        .processes(3, || Box::new(Participant))
        .processes(1, || Box::new(Third))
        .workload_factory(move || {
            Box::new(InterfacesWorkload::new(
                config.clone(),
                Arc::clone(&records),
            ))
        })
        .fault_factory(|| Box::new(InterfaceFaults))
        .enable_chaos([Chaos::Network(ChaosMode::Swarm), Chaos::BuggifyKnobs])
        .chaos_duration(Duration::from_secs(8))
}
