[package]
name = "moonpool-simulation"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2.0"
