//! Rendering of the measured envelopes as moonpool Rust source.
//!
//! The output is plain text on stdout, so a run can be redirected straight into
//! a source file:
//!
//! ```text
//! moonpool-calibrate storage > measured_storage.rs
//! ```
//!
//! Everything else — progress, percentiles, the file being written to — goes to
//! stderr, so the redirected stream stays valid Rust.
//!
//! The emitted constants use the moonpool API as it exists today:
//! [`LatencyDistribution::Uniform { start, end }`][ld]. Nothing new is invented
//! here; the generator only fills in bounds a human would otherwise guess.
//!
//! [ld]: https://docs.rs/moonpool-sim/latest/moonpool_sim/enum.LatencyDistribution.html

use std::fmt::Write as _;
use std::time::Duration;

use crate::stats::{Bounds, Summary};

/// One generated `pub const` item.
#[derive(Debug, Clone)]
pub struct Constant {
    /// The constant's name, e.g. `STORAGE_READ_LATENCY`.
    pub name: String,
    /// One-line summary rendered as the first doc line.
    pub headline: String,
    /// The `p01..p99` envelope the constant carries.
    pub bounds: Bounds,
    /// Percentile detail rendered as the second doc paragraph, when available.
    pub detail: Option<Summary>,
}

impl Constant {
    /// Build a constant from an operation summary, using its `p01..p99` bounds.
    #[must_use]
    pub fn from_summary(name: &str, headline: &str, summary: Summary) -> Self {
        Self {
            name: name.to_owned(),
            headline: headline.to_owned(),
            bounds: summary.bounds(),
            detail: Some(summary),
        }
    }

    /// Build a constant from bounds that were derived rather than measured
    /// directly (the one-way network delay, halved from the round trip).
    #[must_use]
    pub fn from_bounds(name: &str, headline: &str, bounds: Bounds) -> Self {
        Self {
            name: name.to_owned(),
            headline: headline.to_owned(),
            bounds,
            detail: None,
        }
    }
}

/// A complete generated file: a provenance header plus an ordered list of
/// constants.
///
/// Constants are emitted in the order they were pushed, so two runs over the
/// same measurements produce byte-identical output.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    command: String,
    notes: Vec<String>,
    constants: Vec<Constant>,
}

impl GeneratedFile {
    /// Start a file that records `command` as the invocation that produced it.
    #[must_use]
    pub fn new(command: impl Into<String>) -> Self {
        Self {
            command: command.into(),
            notes: Vec::new(),
            constants: Vec::new(),
        }
    }

    /// Add a provenance line to the header comment.
    #[must_use]
    pub fn note(mut self, note: impl Into<String>) -> Self {
        self.notes.push(note.into());
        self
    }

    /// Append a constant. Emission order follows insertion order.
    #[must_use]
    pub fn constant(mut self, constant: Constant) -> Self {
        self.constants.push(constant);
        self
    }

    /// Render the file as rustfmt-clean Rust source.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("// Generated by moonpool-calibrate. Do not edit by hand.\n");
        out.push_str("//\n");
        out.push_str("// Measured on the real host through raw std I/O and std::time::Instant.\n");
        out.push_str("// moonpool is deliberately bypassed during measurement: these are the\n");
        out.push_str("// bounds of the environment the simulation is meant to imitate.\n");
        out.push_str("//\n");
        out.push_str("// Bounds are the p01..p99 envelope of the samples, not min..max, so a\n");
        out.push_str("// single scheduler hiccup cannot widen the simulated world.\n");
        out.push_str("//\n");
        let _ = writeln!(out, "// Command: {}", self.command);
        for note in &self.notes {
            let _ = writeln!(out, "// {note}");
        }
        out.push('\n');
        out.push_str("use moonpool::LatencyDistribution;\n");
        out.push_str("use std::time::Duration;\n");

        for constant in &self.constants {
            out.push('\n');
            let _ = writeln!(out, "/// {}", constant.headline);
            if let Some(detail) = &constant.detail {
                out.push_str("///\n");
                let _ = writeln!(out, "/// {}", describe(detail));
            }
            let _ = writeln!(
                out,
                "pub const {}: LatencyDistribution = LatencyDistribution::Uniform {{",
                constant.name
            );
            let _ = writeln!(
                out,
                "    start: {},",
                duration_literal(constant.bounds.start)
            );
            let _ = writeln!(out, "    end: {},", duration_literal(constant.bounds.end));
            out.push_str("};\n");
        }

        out
    }
}

/// Render a percentile summary as one doc-comment line.
fn describe(summary: &Summary) -> String {
    format!(
        "p01 {:?}, p50 {:?}, p95 {:?}, p99 {:?}, max {:?}, n = {}.",
        summary.p01, summary.p50, summary.p95, summary.p99, summary.max, summary.count
    )
}

/// Render a duration as a `Duration::from_*` constructor call.
///
/// The largest unit that represents the value *exactly* wins. This is not only
/// nicer to read: clippy's pedantic `duration_suboptimal_units` fires on
/// `Duration::from_nanos(19_000)` in the consuming crate, so generated code that
/// always reached for nanoseconds would land its users a lint.
fn duration_literal(duration: Duration) -> String {
    const MICRO: u64 = 1_000;
    const MILLI: u64 = 1_000_000;
    const SEC: u64 = 1_000_000_000;

    let nanos = u64::try_from(duration.as_nanos()).unwrap_or(u64::MAX);
    let (unit, value) = if nanos != 0 && nanos.is_multiple_of(SEC) {
        ("from_secs", nanos / SEC)
    } else if nanos != 0 && nanos.is_multiple_of(MILLI) {
        ("from_millis", nanos / MILLI)
    } else if nanos != 0 && nanos.is_multiple_of(MICRO) {
        ("from_micros", nanos / MICRO)
    } else {
        ("from_nanos", nanos)
    };
    format!("Duration::{unit}({})", grouped_digits(value))
}

/// A number with `_` digit grouping, as Rust source.
fn grouped_digits(value: u64) -> String {
    let digits = value.to_string();
    let mut grouped = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index).is_multiple_of(3) {
            grouped.push('_');
        }
        grouped.push(digit);
    }
    grouped
}

#[cfg(test)]
mod tests {
    use super::{Constant, GeneratedFile, duration_literal, grouped_digits};
    use crate::stats::{Bounds, Summary};
    use std::time::Duration;

    fn summary(name: &'static str) -> Summary {
        Summary {
            name,
            p01: Duration::from_nanos(1_234),
            p50: Duration::from_nanos(1_900),
            p95: Duration::from_nanos(3_100),
            p99: Duration::from_nanos(4_500),
            max: Duration::from_micros(19),
            count: 1_000,
        }
    }

    #[test]
    fn groups_digits_for_readability() {
        assert_eq!(grouped_digits(7), "7");
        assert_eq!(grouped_digits(999), "999");
        assert_eq!(grouped_digits(1_000), "1_000");
        assert_eq!(grouped_digits(1_234_567), "1_234_567");
    }

    #[test]
    fn picks_the_largest_unit_that_is_exact() {
        assert_eq!(
            duration_literal(Duration::from_nanos(1_234)),
            "Duration::from_nanos(1_234)"
        );
        assert_eq!(
            duration_literal(Duration::from_micros(180)),
            "Duration::from_micros(180)"
        );
        assert_eq!(
            duration_literal(Duration::from_millis(3)),
            "Duration::from_millis(3)"
        );
        assert_eq!(
            duration_literal(Duration::from_secs(2)),
            "Duration::from_secs(2)"
        );
        assert_eq!(
            duration_literal(Duration::ZERO),
            "Duration::from_nanos(0)",
            "zero must not be promoted to a larger unit"
        );
        assert_eq!(
            duration_literal(Duration::from_nanos(1_500_500)),
            "Duration::from_nanos(1_500_500)"
        );
    }

    #[test]
    fn renders_a_stable_golden_file() {
        let rendered = GeneratedFile::new("moonpool-calibrate storage")
            .note("Samples: 1000 per operation (after 50 warmup iterations).")
            .constant(Constant::from_summary(
                "STORAGE_READ_LATENCY",
                "Measured storage read latency.",
                summary("read"),
            ))
            .render();

        let expected = "\
// Generated by moonpool-calibrate. Do not edit by hand.
//
// Measured on the real host through raw std I/O and std::time::Instant.
// moonpool is deliberately bypassed during measurement: these are the
// bounds of the environment the simulation is meant to imitate.
//
// Bounds are the p01..p99 envelope of the samples, not min..max, so a
// single scheduler hiccup cannot widen the simulated world.
//
// Command: moonpool-calibrate storage
// Samples: 1000 per operation (after 50 warmup iterations).

use moonpool::LatencyDistribution;
use std::time::Duration;

/// Measured storage read latency.
///
/// p01 1.234\u{b5}s, p50 1.9\u{b5}s, p95 3.1\u{b5}s, p99 4.5\u{b5}s, max 19\u{b5}s, n = 1000.
pub const STORAGE_READ_LATENCY: LatencyDistribution = LatencyDistribution::Uniform {
    start: Duration::from_nanos(1_234),
    end: Duration::from_nanos(4_500),
};
";
        assert_eq!(rendered, expected);
    }

    #[test]
    fn rendering_is_deterministic_and_keeps_insertion_order() {
        let file = GeneratedFile::new("moonpool-calibrate storage")
            .constant(Constant::from_bounds(
                "STORAGE_READ_LATENCY",
                "read",
                Bounds {
                    start: Duration::from_nanos(1),
                    end: Duration::from_nanos(2),
                },
            ))
            .constant(Constant::from_bounds(
                "STORAGE_WRITE_LATENCY",
                "write",
                Bounds {
                    start: Duration::from_nanos(3),
                    end: Duration::from_nanos(4),
                },
            ))
            .constant(Constant::from_bounds(
                "STORAGE_SYNC_LATENCY",
                "sync",
                Bounds {
                    start: Duration::from_nanos(5),
                    end: Duration::from_nanos(6),
                },
            ));

        let first = file.render();
        assert_eq!(first, file.render());

        let read = first.find("STORAGE_READ_LATENCY").expect("read constant");
        let write = first.find("STORAGE_WRITE_LATENCY").expect("write constant");
        let sync = first.find("STORAGE_SYNC_LATENCY").expect("sync constant");
        assert!(read < write);
        assert!(write < sync);
    }

    #[test]
    fn generated_source_is_formatted_conservatively() {
        let rendered = GeneratedFile::new("moonpool-calibrate network measure host-b:7777")
            .note("Samples: 10000.")
            .constant(Constant::from_summary(
                "NETWORK_RTT_LATENCY",
                "Measured small-message TCP round-trip time.",
                summary("rtt"),
            ))
            .render();

        assert!(rendered.ends_with("};\n"));
        assert!(!rendered.contains('\t'));
        for line in rendered.lines() {
            assert!(line.chars().count() <= 100, "line too long: {line}");
            assert_eq!(line.trim_end(), line, "trailing whitespace: {line:?}");
        }
        assert_eq!(
            rendered.matches('{').count(),
            rendered.matches('}').count(),
            "unbalanced braces"
        );
    }

    #[test]
    fn generated_bounds_are_never_inverted() {
        let constant = Constant::from_summary("X", "x", summary("read"));
        assert!(constant.bounds.start <= constant.bounds.end);
    }
}
